# Master python  with numpy for data science and machine learning - Udemy

Cristian Rafael Mendoza Maldonado 2021

# sección 1: Instalación Numpy

Instalando anaconda podemos adquirir esta libreria

# Sección 2: Bases en Numpy
## Capitulo 2.1 : Inicios en Numpy

In [2]:
import numpy as np  # importamos la libreria y la renombramos como se desee np en este caso

In [4]:
'iniciando la creación de un arreglo'
np.array([3,5,4]) #creamos el primer arreglo numpy 
np.__version__ # podemos preguntar por la version de numpy instalada 

' velocidad de computo '
array1 = np.arange(10000) #creamos contadores en forma de arreglos con funciones de la libreria y guardarlos en memoria
array2 = list(range(10000)) # crear listas a partir de funciones numpy

'''%time sirve para medir el tiempo de computo de un bloque de codigo'''

'Deseamos multiplicar cada elemento de la lista por 2 usando arreglos numpy y listas'
time_1 = %time for i in range(10): my_array1 = array1*2
time_2 = %time for i in range(10): my_array2 = [x*2 for x in array2]

Wall time: 1.04 ms
Wall time: 20.3 ms


#### Uso de herramientas de ayuda

Simpre puedes usar la funcion help() para preguntar por ayudas y la documentacion de cada herramienta. De la siguiente forma:

help() : cuadro de dialogo para introducir palabra clave 

help( 'nombre de la funcion') : documentacion de la funcion preguntada


help(np.doc.basics) :  Documentacion basica de la libreria numpy

### help()

Tambien puedes usar el signo de interrogacion directamente para preguntar que hace cierta parte del codigo 

Usando los comandos :

1. shitf + TAB : te dara la documentacion de la funcion en una pestaña

2. np??  -  np.arange?  :  te dara la informacion para su uso

## Capitulo 2.2 : Crear un Ndarray

In [3]:
        '''usando las listas podemos crear una secuencia de numeros de la forma '''
lista = list(range(10))
print('1. lista: ', lista)

        '''usando arreglos numpy a partir de esta lista tenemos que:'''
arreglo = np.array(lista)
arreglo # si el uso del metodo print tenemos apra los arreglos la palabra array([]) para especificar
print('2. arreglo: ', arreglo) # aparecen sin comas

        ''''podemos tener ademas listas dentro de las listas '''
lista_doble = [list(range(5)), list(range(6,11))]
print ('3. lista doble: ' , lista_doble)
arreglo_2 = np.array(lista_doble) #nuevamente creamos un arreglo a partir de una lista
print ('4. arreglo 2: ', arreglo_2)

        '''podemos preguntarnos por las dimensiones de los arreglos haciendo '''
print('5. dim arreglo: ', arreglo.ndim, '  dim arreglo 2: ', arreglo_2.ndim, '  shape arreglo 2: ', arreglo_2.shape)


        '''probemos ahora para un arreglo de 3 dimensiones'''
lista_3 =[[[0, 1], [2, 3], [6, 7]], [[0, 1], [2, 3], [6, 7]], [[0, 1], [2, 3], [6, 7]]] 
print('6. lista 3:', lista_3)
arreglo_3 = np.array(lista_3)
print('7. arreglo 3:' )
print(arreglo_3)
print('8. dim arreglo 3: ', arreglo_3.ndim, 'shape arreglo 3:', arreglo_3.shape)

        ''' si se desea ver el tipo de datos dentro de un arreglo podemos hacer'''
print('9. tipo de datos arreglo 3:', arreglo_3.dtype)

        '''si dentro de una lista hay numeros flotantes, el arreglo que surga de ella sera de tipo de numeros flotantes'''
arreglo_4 = np.array([3 , 5 , 6 , 7 , 4.5 , 6 , 9])
print('9. arreglo 4:' ,arreglo_4, 'tipos de datos ', arreglo_4.dtype)

        '''hay arreglos muy utiles de usar como son aquellos llenos de ceros y de unos, veamos como se usan'''
    
ceros = np.zeros(3) #matrices de ceros 
print('10. ceros:' ,ceros)

ceros_2 = np.zeros((2,7)) #se le puede dar de argumento la forma de la matriz 
print('11. ceros 2:')
print(ceros_2)

ceros_3 = np.zeros((3,4,5)) # e incluso se pueden hacer de dimensiones incluso mayores
print('12. ceros 3 :' )
print(ceros_3)

unos_2 = np.ones((2,5)) # de igual forma funciona para las matrices de unos 
print('13. unos 2 :')
print(unos_2)

vacio = np.empty((2,4)) # matrices vacias 
print('14. vacio :' )
print(vacio)

contador = np.arange(10) #arreglos de contadores 
print('15. contador- arange:' , contador)

contador_2 = np.arange(2,18, 2) # se pueden dar limites y cada tanto contar
print('16. contador 2:' , contador_2)

identidad = np.eye(5) # finalmente para las matrices identidad
print('17. I_5 =')
print(identidad)

1. lista:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
2. arreglo:  [0 1 2 3 4 5 6 7 8 9]
3. lista doble:  [[0, 1, 2, 3, 4], [6, 7, 8, 9, 10]]
4. arreglo 2:  [[ 0  1  2  3  4]
 [ 6  7  8  9 10]]
5. dim arreglo:  1   dim arreglo 2:  2   shape arreglo 2:  (2, 5)
6. lista 3: [[[0, 1], [2, 3], [6, 7]], [[0, 1], [2, 3], [6, 7]], [[0, 1], [2, 3], [6, 7]]]
7. arreglo 3:
[[[0 1]
  [2 3]
  [6 7]]

 [[0 1]
  [2 3]
  [6 7]]

 [[0 1]
  [2 3]
  [6 7]]]
8. dim arreglo 3:  3 shape arreglo 3: (3, 3, 2)
9. tipo de datos arreglo 3: int32
9. arreglo 4: [3.  5.  6.  7.  4.5 6.  9. ] tipos de datos  float64
10. ceros: [0. 0. 0.]
11. ceros 2:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
12. ceros 3 :
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
13. unos 2 :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
14. vacio :
[[0.0e+000 0.0e+000 0.0e+

# capitulo 2.3: Tipo de datos / dType

Aquí veremos los tipos de datos que podemos utilizar en numpy

In [26]:
        ''' en la mayoria de las funciones numpy se le puede seleccionar el tipo de datos que se desea '''
array_31 = np.array(list(range(4)), dtype = np.float64)
array_32  = np.array(list(range(4)), dtype = np.int32)
print('1. el mismo arreglo de dos tipos diferentes: ',array_31, '/', array_32)


        '''una forma mas abreviada de escribirlo es:'''
array_33 = array_31.astype(np.int32)
print('2. cambiando el tipo de datos en el arreglo_31 : ' , array_33)


        ''' se hace util cambiar una lista de tipo numerico  a elementos string, hacemos lo mismo  '''
array_34 = np.array([3,4,6,8,9,12,33], dtype = np.string_)
array_35 = array_31.astype(np.string_)
print('3. arreglos string: ', array_34,'  ', array_35 )


        '''un ejemplo practico es cuando quieres usar una lista para nombrar las curvas en una grafica'''
nombres = np.array(list(range(10)), dtype = np.string_)
print ('4. nombres : ', nombres) #aparecen con las letas 'b' al inicio

        '''de igual forma podemos pasar strings de numeros al tipo numerico'''
numeros = nombres.astype(np.int32)
print('5. regresando a números : ', numeros)

        '''usamos ahora la funcion arange porque es mejor para estos conteos que hacemos'''
array_36 = np.arange(15) # empieza en 0 y llega hasta el n-1 = 14, con typo int
print('6. arreglo 36 usando funcion arange: ', array_36)

        '''finalmente hay un tipo mas de datos, el u8'''
vacio = np.empty(3, dtype = 'u8')
print('7. el arreglo de vacio: ' , vacio) # por aclarar que hace

1. el mismo arreglo de dos tipos diferentes:  [0. 1. 2. 3.] / [0 1 2 3]
2. cambiando el tipo de datos en el arreglo_31 :  [0 1 2 3]
3. arreglos string:  [b'3' b'4' b'6' b'8' b'9' b'12' b'33']    [b'0.0' b'1.0' b'2.0' b'3.0']
4. nombres :  [b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9']
5. regresando a números :  [0 1 2 3 4 5 6 7 8 9]
6. arreglo 36 usando funcion arange:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
7. el arreglo de vacio:  [4607182418800017408 4611686018427387904 4613937818241073152]


# Capitulo 2.4: Pseudo-random generación de números

Dentro de la libreria numpy existe la seccion random, esta es la que vamos a usar. Para ello vamos a importarla de forma particular y etiquetarla para mayor comodidad

In [21]:
import numpy.random as r

        'probemos usar la funcion randn la cual genera numero "aleatorios"''
s1 = r.randn()
s2 = r.randn(3)
s3 = r.randn(2,3)
s4 = r.randn(3,2,2)

print('1. diferentes dimensiones y formas de arreglos con numeros aleatorios: ' )
print('s1 = ', s1,'s2 = ',  s2,'s3 = ',s3)
print('s4 = ',s4)

        '''se se desea se puede escoguer valores random de la distribucion gauseana, la campana de gauss'''
s5 = r.normal(size = (4,2)) # le agregamos las dimensiones deseas en este caso 
print('2. Matriz de valores dist. Normal: ', s5)
r.seed(1234)#por averiguar que hace la funcion r.seed()

        '''podemos tambien generar numeros enteros aleatorios usando randint'''
s6 = r.randint(5, 10) # se le introduce los limites sobre los cuales tomara dicho numero pseduo aleatorio
print ('3. entero aleatorio generado:' , s6)
 
        '''podemos hacer un reshape a un conjunto de datos para transformarlo a la forma que queramos'''
s7 = r.randn(2,3)
print('4. transformar un conjunto de datos aleatorios a la forma que deseemos :')
print(s7 ,s7.reshape(1,6))

        '''podemos crear arreglos de numeros desde un arreglo inicialmente aleatorio'''
arreglo_aleatorio = r.RandomState(1234)
s8 = arreglo_aleatorio.rand(4) # arreglo random
s9 = arreglo_aleatorio.randint(10) #numero entero random
s10 = arreglo_aleatorio.normal(10) #desde la distribucion normal
s11 =  arreglo_aleatorio.uniform(10) #desde una distribucion uniforme (unidad)

print ('5. los diferentes tipos de arreglos aleatorios que se pueden usar una a partir de un arreglo aleatorio inicial, a cada compilacion daran nuevos valores.')
print ('s8: ', s8 )
print('s9: ', s9) 
print('s10: ', s10)
print ('s11: ', s11)

1. diferentes dimensiones y formas de arreglos con numeros aleatorios: 
s1 =  -0.33060681994142005 s2 =  [0.87412791 2.00254961 0.01086208] s3 =  [[-0.86924706  1.4249841   0.1458091 ]
 [ 2.89409095 -0.30426018  0.861661  ]]
s4 =  [[[-0.68992667  0.18749737]
  [ 0.60430874 -0.18301422]]

 [[-1.12650247  1.65887284]
  [-0.66044141  1.04108597]]

 [[ 1.05317489  0.1942955 ]
  [ 1.35835198 -0.28694235]]]
2. Matriz de valores dist. Normal:  [[ 0.44143825 -0.76987271]
 [-0.97456841  0.70900741]
 [-0.10578273  0.77677573]
 [ 0.91395164  1.68912124]]
3. entero aleatorio generado: 8
4. transformar un conjunto de datos aleatorios a la forma que deseemos :
[[-1.0336313   2.02683258  0.66250904]
 [ 0.67524634 -0.94029827 -0.95658428]] [[-1.0336313   2.02683258  0.66250904  0.67524634 -0.94029827 -0.95658428]]
5. los diferentes tipos de arreglos aleatorios que se pueden usar una a partir de un arreglo aleatorio inicial, a cada compilacion daran nuevos valores.
s8:  [0.19151945 0.62210877 0.4377277

# seccion 3: Indexación en numpy

## Capitulo 3.1: Indexing and Slicing 



In [59]:
        'Creamos un nuevo arreglo y utilizamos la indexación para seleccionar un elemento de está'

sc31 = np.array(np.arange(10))
print('1. nuevo arreglo sobre el cual se trabajara:' , sc31)
print('2. sc3_1 elemento en la posición 3: ', sc31[3])

        'se puede tambien seleccionar una seccion de este arreglo limitando las posiciones seleccionadas'
print('3. seleccionando un rango de limites: ', sc31[2:6])
        
        'puedes reescribir los elementos en un arreglo igualandolo a un valor concreto'
sc31[2:6] = 5
print('4. arreglo de datos con introduccion del 5 en las posiciones [2:6] : ', sc31)

        'Además a partir de la selección de un grupo de datos podemos crear un nuevo arreglo'
sc32 = sc31[2:6]
print('5. nuevo arreglo a partir de la selección de sc31: ', sc32)

        'se puede cambiar el valor de un elemento en especifico por otro, asi como de todos los valores de esta'
sc31[5] = 50
print('6. cambiando un valor de arreglo "sc31[5] = 50" :', sc31)
sc32[:] = 20
print('7. Cambiando todos los elementos de un arreglo "sc32[:] = 20" : ', sc32)

        'creando un nuevo arreglo de 2 dimensiones; se puede seleccionar elementos pero habrá que seleccionar sus coordenadas [i][j]'
sc33 = np.arange(9).reshape(3,3)
print('8. arreglo 2dim inicial sc33:' )
print(sc33)
print ('9. Se seleciona las posiciones de un elemento en 1 dim y en 2 dim: ')
print('sc33[2] =  ',sc33[2],'/ sc33[2][1] = ' ,sc33[2][1])

        'Tambien se puede seleccionar una posición de forma más comoda usando comas A[a,b]'
print('10.  usando la sintaxis A[a,b] : sc33[2,1] = ', sc33[2,1])

        'De forma analoga para 3 o mas dimensiones'
    
sc34 = np.arange(12).reshape(2,2,3)
print('11. matriz de 3 dimensiones:')
print(sc34)
print('12. Seleccionando el elemento A[a,b,c]: sc34[0,1,2] =  ', sc34[0,1,2])

        'con el método np.copy() podemos copiar un arreglo en otro'
sc35 = sc34[0,0].copy()
print('13. Usando np.copy() para copiar un arreglo, copiamos una parte de la matriz sc34: ', sc35)


        'Se aplican las mismas operaciones vistas anteriormente de reemplazo de elementos en los arreglos'
sc34[0] = 100
print('14. Reemplazando valores sc34[0] = 100 : ')
print(sc34)


        'se puede limitar un maximo o minimo para la seleccion de elementos incluso si estos son arreglos dentro de otros '
print ( '15. seleccion sc34[1:,1]  :')
print(sc34[1:,1]) # la seleccion se hace de la siguiente forma [ inf:sup ,inf:sup , inf:sup , ...] dependiendo de las dimensiones del arreglo.
print('16. De una forma mas interesante se puede seleccionar solo un recaudro del arreglo (area, volumen, n-volumen): ')
print('de la siguiente forma sc34[1:,:1]')
print (sc34[1:,:1])

        'Veamos un poco mas el PODER  de esta herramienta'
sc36 = np.arange(125).reshape(5,5,5) # cubo de datos de arista 5
    #se selecciona un pedazo de este volumen
print ('17. volumen de datos de arista 5: ' )
print (sc36) # mirando la correspondencia de los datos se puede ver un  cubo laminar L = 5
print ('seleccionamos unicamente un cubo de arista 3')
print (sc36[:3,:3,:3]) # se recortan de las laminas otras mas pequeñas de arista L = 3
print('puede ser incluso un hilo de este cubo: ')
print(sc36[0,:,0]) # realmente impresionante ahora que por primera vez lo voy entendiendo

        'probemos ahora cambiar los valores de una parte de este cubo'
    
sc36[:,1:4,1:4] = 25
print('18. Cambiando los valores de una parte de este cubo: ')
print(sc36)



1. nuevo arrelo sobre el cual se trabajara: [0 1 2 3 4 5 6 7 8 9]
2. sc3_1 elemento en la posición 3:  3
3. seleccionando un rango de limites:  [2 3 4 5]
4. arreglo de datos con introduccion del 5 en las posiciones [2:6] :  [0 1 5 5 5 5 6 7 8 9]
5. nuevo arreglo a partir de la selección de sc31:  [5 5 5 5]
6. cambiando un valor de arreglo "sc31[5] = 50" : [ 0  1  5  5  5 50  6  7  8  9]
7. Cambiando todos los elementos de un arreglo "sc32[:] = 20" :  [20 20 20 20]
8. arreglo 2dim inicial sc33:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
9. Se seleciona las posiciones de un elemento en 1 dim y en 2 dim: 
sc33[2] =   [6 7 8] / sc33[2][1] =  7
10.  usando la sintaxis A[a,b] : sc33[2,1] =  7
11. matriz de 3 dimensiones:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
12. Seleccionando el elemento A[a,b,c]: sc34[0,1,2] =   5
13. Usando np.copy() para copiar un arreglo, copiamos una parte de la matriz sc34:  [0 1 2]
14. Reemplazando valores sc34[0] = 100 : 
[[[100 100 100]
  [100 100 100]]

 [[  6  

## Capitulo 3.2: boolean indexing

Podemos ingresar indexacion a partir de elementos booleanos a pesar que la indexacion en numpy solo acepte directamente enteros.

In [53]:
        'Aprender el uso de indexación con string'

colores = np.array(['rojo', 'azul','verde' , 'rojo', 'azul','verde' ,'rojo', 'azul','verde','rojo']) # creamos un arreglo con elementos string
datos = np.arange(40).reshape(10,4) #creamos una matriz con elementos 
print('1. Mostramos la matriz de datos creadas: ')
print(datos)

        'eleccionamos el valor booleano de cada elemento del arreglo colores'
# es fundamental que el arreglo de seleccion y el arreglo de elementos (a seleccionar) tengan las mismas dimensiones
print('2. selecion de valor booleano de colores == rojo :', colores == 'rojo') 
        
        'seleccionar a partir de valores booleanos el elemento de un arreglo'
print('3. datos [colores == rojo] : ')
print(datos[colores=='rojo']) # para este caso se selecciona un elemento de dim (4,)

        'escojamos ahora los elementos de esta nueva matriz'
print('4. escoguiendo un sub matriz de está: datos[colores == rojo, 1:]')
print(datos[colores == 'rojo',1:])
print('5. seleccionando elementos')
print(datos[colores == 'rojo', 1] )

        'si se desea negar la condición se usa !=  o ~ '
print('6. negando la condicion booleana anterior datos[colores != rojo ]: ')
print(datos[colores != 'rojo' ])

        'si se desea tomar más de una condición de puede usar el simbolo |'
print('7. usar una condicion u otra')
condiciones = (colores == 'rojo') | (colores == 'azul')
print(datos[condiciones])

        'se  puede usar una desigualdad como condicion de seleccion (muy util)'
print('8. arreglo de numeros para usar como condicion de seleccion :')
numeros = np.arange(10)

print('9. datos con la seleccion de lista numeros menores estrictos a 8:')
print(datos[numeros <8])

# ademas se puede seleccionar por ambos lados 
print('10. y seleccion de estos desde el elemento 0 al 2 de cada fila:')
print(datos[numeros<8, :2 ])

        'se pueden usar los propios valores del arreglo como criterio de selecion '
    #EL PROPIO ARREGLO! prácticamente es aprender a hablar y pedirle las cosas comodamente
print('11. seleccionando solo aquellos datos menores a 25: ')
print(datos[datos<25])

        'finalmente podemos no solo seleccionar si no reemplazar todos estos valores de un arreglo n dim por otros dados manualmente'
print('12. reemplazando datos[datos < 30] = 7: ')
datos[datos<30] = 7
print(datos)



1. Mostramos la matriz de datos creadas: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
2. selecion de valor booleano de colores == rojo : [ True False False  True False False  True False False  True]
3. datos [colores == rojo] : 
[[ 0  1  2  3]
 [12 13 14 15]
 [24 25 26 27]
 [36 37 38 39]]
4. escoguiendo un sub matriz de está: datos[colores == rojo, 1:]
[[ 1  2  3]
 [13 14 15]
 [25 26 27]
 [37 38 39]]
5. seleccionando elementos
[ 1 13 25 37]
6. negando la condicion booleana anterior datos[colores != rojo ]: 
[[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [28 29 30 31]
 [32 33 34 35]]
7. usar una condicion u otra
[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]
 [16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [36 37 38 39]]
8. arreglo de numeros para usar como condicion de seleccion :
9. datos con la seleccion de lista numeros menores estrictos a 8:
[[ 0  1  2  3]
 [ 4  5  6 

# capitulo 3.3: Indexacion Manual 

In [55]:
  'creando una lista manualmente de los elementos que deseamos seleccionar de un arreglo'
    
a_33 = np.arange(100).reshape(20,5)
lista33 = [4,5,8,12,16,18]
print('1. mostramos el arreglo con que se inicia:')
print(a_33)
print('2. Seleccionando los elementos de un arreglo a partir de una lista manual:')
print(a_33[lista33])

1. mostramos el arreglo con que se inicia
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
2. Seleccionando los elementos de un arreglo a partir de una lista manual
[[20 21 22 23 24]
 [25 26 27 28 29]
 [40 41 42 43 44]
 [60 61 62 63 64]
 [80 81 82 83 84]
 [90 91 92 93 94]]
